development:
  adapter: postgresql
  database: rails_api
  encoding: utf8
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: rails_api
  encoding: utf8
  LC_CTYPE: 'en_US.UTF-8'
  LC_COLLATE: 'en_US.UTF-8'
  pool: 5
  timeout: 5000
